/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ModelBeans.BeansCadCliente;
import ModelBeans.BeansLocacao;
import ModelConection.ConexaoBD;
import ModelDao.DaoCadCliente;
import ModelDao.DaoLocacao;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author peterson
 */
public class TelaLocacao extends javax.swing.JFrame {
    
   ModelConection.ConexaoBD conexao = new ConexaoBD();
    ArrayList<BeansCadCliente> clientes = new ArrayList<>();
            
    public TelaLocacao() {
        initComponents();
        
        preencherClientes();
        preencherTabelaFilmes("select * from filme order by nome");
        jTextFieldTotal.setText("0.0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFilmes = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableLocacao = new javax.swing.JTable();
        jTextFieldTotal = new javax.swing.JTextField();
        jButtonRemover = new javax.swing.JButton();
        jTextFieldBuscaFilme = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonRealizarLocacao = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jDateChooserLocacao = new com.toedter.calendar.JDateChooser();
        jDateChooserDevolucao = new com.toedter.calendar.JDateChooser();
        jComboBoxClientes = new javax.swing.JComboBox<>();
        jButtonAdicionarNaTabela = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Locação");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 100, 17);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 128, 0));
        jLabel2.setText("Cliente");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 190, 190, 21);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 128, 0));
        jLabel3.setText("Buscar Filmes");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(430, 40, 210, 30);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 128, 0));
        jLabel4.setText("Data de Locação");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 270, 120, 18);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 128, 0));
        jLabel5.setText("Data de Devolução");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 310, 140, 18);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 128, 0));
        jLabel6.setText("Total");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 350, 36, 18);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 128, 0));
        jLabel7.setText("Filmes a serem alugados");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(430, 290, 220, 20);

        jTableFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Premonição", "Horror", "2", "3,00"},
                {"Jacaré mortal", "Horror", "1", "3,00"},
                {"Saci Pererê O retorno", "Terror", "1", "3,00"},
                {"Ps. Te amo", "Horror", "1", "1,50"},
                {"Saw II", "Horror", "2", "3,00"},
                {"Forest Gump o contador de historias", "Classicos", "1", "3,00"}
            },
            new String [] {
                "Filme", "Categoria", "Estoque", "Valor"
            }
        ));
        jScrollPane2.setViewportView(jTableFilmes);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(430, 80, 570, 150);

        jTableLocacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableLocacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLocacaoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableLocacao);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(430, 320, 570, 180);

        jTextFieldTotal.setEnabled(false);
        jTextFieldTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTotal);
        jTextFieldTotal.setBounds(170, 340, 180, 27);

        jButtonRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lixeira20.png"))); // NOI18N
        jButtonRemover.setText("Remover Filme da lista");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRemover);
        jButtonRemover.setBounds(650, 280, 200, 32);

        jTextFieldBuscaFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscaFilmeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldBuscaFilme);
        jTextFieldBuscaFilme.setBounds(560, 40, 290, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buscar20.png"))); // NOI18N
        jButton2.setText(" Pesquisa");
        jPanel1.add(jButton2);
        jButton2.setBounds(860, 40, 140, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(-10, 60, 390, 120);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calendario aluga25.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(360, 260, 25, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calendario devoluçap 25.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(360, 300, 25, 25);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/dinheiro 25.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(360, 340, 25, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/jigsaw 30.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(360, 220, 40, 30);

        jButtonRealizarLocacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salvar.png"))); // NOI18N
        jButtonRealizarLocacao.setText(" Realizar locação e Salvar");
        jButtonRealizarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarLocacaoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRealizarLocacao);
        jButtonRealizarLocacao.setBounds(160, 420, 250, 50);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/voltar.png"))); // NOI18N
        jButtonVoltar.setText(" Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVoltar);
        jButtonVoltar.setBounds(20, 420, 130, 50);
        jPanel1.add(jDateChooserLocacao);
        jDateChooserLocacao.setBounds(170, 260, 180, 27);
        jPanel1.add(jDateChooserDevolucao);
        jDateChooserDevolucao.setBounds(170, 300, 180, 27);

        jComboBoxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClientesActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxClientes);
        jComboBoxClientes.setBounds(20, 220, 330, 27);

        jButtonAdicionarNaTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adicionar filme 20.png"))); // NOI18N
        jButtonAdicionarNaTabela.setText(" Adicionar a lista");
        jButtonAdicionarNaTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarNaTabelaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdicionarNaTabela);
        jButtonAdicionarNaTabela.setBounds(430, 240, 170, 32);

        jLabelFundo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabelFundo.setForeground(new java.awt.Color(255, 128, 0));
        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fundo 2.jpg"))); // NOI18N
        jPanel1.add(jLabelFundo);
        jLabelFundo.setBounds(-10, 30, 1040, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void somarTotal(){
        conexao.conexao();
            conexao.executaSql("SELECT CONCAT( primeiro_nome, ' ', sobrenome) as 'nome' FROM cliente order by primeiro_nome");
            try {
                conexao.rs.first();
                do{
                    jComboBoxClientes.addItem(conexao.rs.getString("nome"));
                }while(conexao.rs.next());
            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null, "Erro ao preencher Clientes \n" + ex.getMessage());
            }
        conexao.desconecta();
    }
    
    public void preencherClientes(){
        
        //DaoCadCliente dao = new DaoCadCliente();
        //clientes = dao.all();
        
        conexao.conexao();
            conexao.executaSql("SELECT CONCAT( primeiro_nome, ' ', sobrenome) as 'nome', id_cliente FROM cliente order by primeiro_nome");
            try {
                conexao.rs.first();
                jComboBoxClientes.removeAllItems();
                do{
                    jComboBoxClientes.addItem(conexao.rs.getString("nome"));
                    
                    BeansCadCliente c = new BeansCadCliente();
                    c.setId(conexao.rs.getInt("id_cliente"));
                    
                    clientes.add( c );
                    
                }while(conexao.rs.next());
            } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(null, "Erro ao preencher Clientes \n" + ex.getMessage());
            }
        conexao.desconecta();
    }
    
    private void jTextFieldBuscaFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscaFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscaFilmeActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaPrincipal telaAnterior = new TelaPrincipal();
        telaAnterior.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jComboBoxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClientesActionPerformed
        
    }//GEN-LAST:event_jComboBoxClientesActionPerformed

    private void jButtonAdicionarNaTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarNaTabelaActionPerformed
        int lineIndex = jTableFilmes.getSelectedRow();    
            if(lineIndex != -1){
        String id =""+jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(),0);  
        //JOptionPane.showMessageDialog(rootPane, nome);
        
        ArrayList dados = new ArrayList();
        String [] colunas = new String [] {"ID", "Nome Filme", "Classificação", "Estoque", "Valor"};
        conexao.conexao();
            conexao.executaSql("SELECT * FROM filme WHERE id_filme LIKE '"+id+"' ");
            try{
               conexao.rs.first();
                   dados.add(new Object[]{conexao.rs.getInt("id_filme"), conexao.rs.getString("nome"), conexao.rs.getString("classificacao_etaria"), conexao.rs.getString("estoque"), conexao.rs.getString("valor_locacao")});
                   
                   Double total = Double.parseDouble(jTextFieldTotal.getText());
                   total += Double.parseDouble(conexao.rs.getString("valor_locacao"));
                   jTextFieldTotal.setText(total.toString());
                   
            }catch (SQLException ex){
                JOptionPane.showMessageDialog(rootPane,"Erro ao preencher tabela");
            }
            
            try{
                ModelBeans.BeansTabela modeloAntigo = (ModelBeans.BeansTabela)jTableLocacao.getModel();
                ArrayList dadosAntigos = modeloAntigo.getLinhas();
                dados.addAll(dadosAntigos);
            }catch(ClassCastException ex){
                System.out.println("Impossivel converter.. tabela ainda nao inicializada!");
            }
            
            ModelBeans.BeansTabela modelo = new ModelBeans.BeansTabela(dados, colunas);
            jTableLocacao.setModel(modelo);
            
            
            // ID
            jTableLocacao.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTableLocacao.getColumnModel().getColumn(0).setResizable(false);
            //PRIMEIRO NOME 
            jTableLocacao.getColumnModel().getColumn(1).setPreferredWidth(288);
            jTableLocacao.getColumnModel().getColumn(1).setResizable(false);
            //CLASSIFICAÇÃO ETÁRIA
            jTableLocacao.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableLocacao.getColumnModel().getColumn(2).setResizable(false);
            //ESTOQUE
            jTableLocacao.getColumnModel().getColumn(3).setPreferredWidth(65);
            jTableLocacao.getColumnModel().getColumn(3).setResizable(false);
            //VALOR LOCAÇÃO
            jTableLocacao.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTableLocacao.getColumnModel().getColumn(4).setResizable(false);
            //NAO PODE REORDENAR O CABEÇALHO DA TABELA
            jTableLocacao.getTableHeader().setReorderingAllowed(false);
            //NAO PODE SER REDIMENCIONADA 
            jTableLocacao.setAutoResizeMode(jTableLocacao.AUTO_RESIZE_OFF);
            //SO PODERA SELECIONAR UM DADO NA TABELA DE CADA VEZ 
            jTableLocacao.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexao.desconecta();
            
        
        // Buscar no banco o objeto referente à variável "nome"
        
        //montar esquema para transferir de uma table para outra
        }
    }//GEN-LAST:event_jButtonAdicionarNaTabelaActionPerformed

    private void jTextFieldTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalActionPerformed

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        try{
            //SÓ IMPRIME O VALOR DA COLUNA DE PREÇO
            ModelBeans.BeansTabela modeloAntigo = (ModelBeans.BeansTabela)jTableLocacao.getModel();
            int lineIndex = jTableLocacao.getSelectedRow();
            
            if(lineIndex != -1){
                
                String preco =""+jTableLocacao.getValueAt(jTableLocacao.getSelectedRow(),4);
                modeloAntigo.getLinhas().remove(lineIndex);
                
                Double total = Double.parseDouble(jTextFieldTotal.getText());
                total -= Double.parseDouble(preco);
                jTextFieldTotal.setText(total.toString());
                
                //jTextFieldTotal.setText(Double.parseDouble(total));
                
                modeloAntigo.fireTableDataChanged();
            }
            
        }catch(ClassCastException ex){
           // System.out.println("Tabela ainda não inicializada!");
        }
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonRealizarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarLocacaoActionPerformed
         BeansLocacao locacao = new BeansLocacao();
         // CLIENTE QUE ESTA REALIZANDO LOCACAO
         locacao.setCliente_locacao(jComboBoxClientes.getSelectedItem().toString());
         // DATA DA LOCAÇAO
         java.sql.Date dataLocacao = new java.sql.Date( jDateChooserLocacao.getDate().getTime() );
         locacao.setData_locacao(dataLocacao);
         // DATA DA DEVOLUÇAO
         java.sql.Date dataDevolucao = new java.sql.Date( jDateChooserDevolucao.getDate().getTime() );
         locacao.setData_devolucao(dataDevolucao);
         //JOptionPane.showMessageDialog(rootPane, dataDevolucao);
         // VALOR TOTAL
         locacao.setTotal(jTextFieldTotal.getText());
         // FILMES QUE ESTAO NA TABELA
      
         locacao.setId_cliente( clientes.get( jComboBoxClientes.getSelectedIndex() ).getId() );
         
         DaoLocacao dao = new DaoLocacao();
         int idLocacao = dao.salvarlocacao(locacao);
         
         
         //String idFilme =""+jTableFilmes.getValueAt(jTableFilmes.getSelectedRow(),0);
         //JOptionPane.showMessageDialog(rootPane, idFilme);
         
         for (int i = 0; i < jTableLocacao.getRowCount(); i++) {
            int idItemLoc = Integer.parseInt(""+jTableLocacao.getValueAt(i, 0));
            dao.salvarItensLocacao(idLocacao,idItemLoc);
        }
        // MENSAGEM DE LOCAÇÃO REALIZADA COM SUCESSO!
         JOptionPane.showMessageDialog(rootPane,"Locação realizada com sucesso!");
        // INSTANCIANDO TELA NOVAMENTE PARA LIMPAR OS CAMPOS LIKE A MCGAIVER
         TelaLocacao tela = new TelaLocacao();
         tela.setVisible(true);
         dispose();
    }//GEN-LAST:event_jButtonRealizarLocacaoActionPerformed

    private void jTableLocacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLocacaoMouseClicked
        //  INICIALIZADA SOMENTE PARA TESTE
    }//GEN-LAST:event_jTableLocacaoMouseClicked

    public void preencherTabelaFilmes(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String [] {"ID", "Nome Filme", "Classificação", "Estoque", "Valor"};
        conexao.conexao();
            conexao.executaSql(Sql);
            try{
               conexao.rs.first();
               do{
                   dados.add(new Object[]{conexao.rs.getInt("id_filme"), conexao.rs.getString("nome"), conexao.rs.getString("classificacao_etaria"), conexao.rs.getString("estoque"), conexao.rs.getString("valor_locacao")});
                   
               }while(conexao.rs.next());
            }catch (SQLException ex){
                JOptionPane.showMessageDialog(rootPane,"Erro ao preencher tabela");
            }
            ModelBeans.BeansTabela modelo = new ModelBeans.BeansTabela(dados, colunas);
            jTableFilmes.setModel(modelo);
            // ID
            jTableFilmes.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTableFilmes.getColumnModel().getColumn(0).setResizable(false);
            //PRIMEIRO NOME 
            jTableFilmes.getColumnModel().getColumn(1).setPreferredWidth(288);
            jTableFilmes.getColumnModel().getColumn(1).setResizable(false);
            //CLASSIFICAÇÃO ETÁRIA
            jTableFilmes.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableFilmes.getColumnModel().getColumn(2).setResizable(false);
            //ESTOQUE
            jTableFilmes.getColumnModel().getColumn(3).setPreferredWidth(65);
            jTableFilmes.getColumnModel().getColumn(3).setResizable(false);
            //VALOR LOCAÇÃO
            jTableFilmes.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTableFilmes.getColumnModel().getColumn(4).setResizable(false);
            //NAO PODE REORDENAR O CABEÇALHO DA TABELA
            jTableFilmes.getTableHeader().setReorderingAllowed(false);
            //NAO PODE SER REDIMENCIONADA 
            jTableFilmes.setAutoResizeMode(jTableFilmes.AUTO_RESIZE_OFF);
            //SO PODERA SELECIONAR UM DADO NA TABELA DE CADA VEZ 
            jTableFilmes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexao.desconecta();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLocacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAdicionarNaTabela;
    private javax.swing.JButton jButtonRealizarLocacao;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxClientes;
    private com.toedter.calendar.JDateChooser jDateChooserDevolucao;
    private com.toedter.calendar.JDateChooser jDateChooserLocacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableFilmes;
    private javax.swing.JTable jTableLocacao;
    private javax.swing.JTextField jTextFieldBuscaFilme;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
}
