/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javafx.scene.input.KeyCode;
import javax.swing.*;
import javax.swing.JTextField;

/**
 *
 * @author peterson
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLoginLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUserLogin = new javax.swing.JTextField();
        jPasswordUserPassword = new javax.swing.JPasswordField();
        jButtonSair = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        JlabelLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelLoginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        getContentPane().add(jLabelLoginLogo);
        jLabelLoginLogo.setBounds(120, 40, 450, 120);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 128, 0));
        jLabel2.setText("User:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 170, 49, 18);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 128, 0));
        jLabel3.setText("Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 230, 90, 18);
        getContentPane().add(jTextFieldUserLogin);
        jTextFieldUserLogin.setBounds(240, 190, 150, 27);

        jPasswordUserPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordUserPasswordActionPerformed(evt);
            }
        });
        jPasswordUserPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordUserPasswordKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordUserPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordUserPassword);
        jPasswordUserPassword.setBounds(240, 250, 150, 27);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(320, 290, 70, 29);

        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jButtonLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonLoginKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonLogin);
        jButtonLogin.setBounds(240, 290, 70, 29);

        JlabelLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plano de fundo login.PNG"))); // NOI18N
        getContentPane().add(JlabelLogin);
        JlabelLogin.setBounds(-30, -40, 730, 570);

        setSize(new java.awt.Dimension(675, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
    
        if(jTextFieldUserLogin.getText().equals("admin")&& jPasswordUserPassword.getText().equals("admin")){
            TelaPrincipal tela = new TelaPrincipal();
            tela.setVisible(true);
            dispose();
    }//GEN-LAST:event_jButtonLoginActionPerformed
        else{
            JOptionPane.showMessageDialog(rootPane,"Usuario ou senha invalidos");
        }
    }
    
    
    
    private void jPasswordUserPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordUserPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordUserPasswordActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jPasswordUserPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordUserPasswordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordUserPasswordKeyPressed

    private void jButtonLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonLoginKeyPressed
         if(jTextFieldUserLogin.getText().equals("admin")&& jPasswordUserPassword.getText().equals("admin")){
            TelaPrincipal tela = new TelaPrincipal();
            tela.setVisible(true);
            dispose();
    }                                            
        else{
            JOptionPane.showMessageDialog(rootPane,"Usuario ou senha invalidos");
        }
    }//GEN-LAST:event_jButtonLoginKeyPressed

    private void jPasswordUserPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordUserPasswordKeyTyped
        // TODO add your handling code here:
        //System.out.println(evt.getKeyChar());
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(jTextFieldUserLogin.getText().toString().equals("admin")&& jPasswordUserPassword.getText().toString().equals("admin")){
                TelaPrincipal tela = new TelaPrincipal();
                tela.setVisible(true);
                dispose();
            }else{
                JOptionPane.showMessageDialog(rootPane,"Os campos Usuario ou senha estão inválidos ou vazios");
            }
        }
    }//GEN-LAST:event_jPasswordUserPasswordKeyTyped

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelLogin;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelLoginLogo;
    private javax.swing.JPasswordField jPasswordUserPassword;
    private javax.swing.JTextField jTextFieldUserLogin;
    // End of variables declaration//GEN-END:variables
}
