/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ModelBeans.BeansDevolucao;
import ModelConection.ConexaoBD;
import ModelDao.DaoDevolucao;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author peterson
 */
public class TelaDevolucao extends javax.swing.JFrame {

    ConexaoBD conexao = new ConexaoBD();
    BeansDevolucao devolucao = new BeansDevolucao();
    DaoDevolucao dao = new DaoDevolucao();
    
    
    /**
     * Creates new form TelaDevolucao
     */
    public TelaDevolucao() {
        initComponents();
        preencherTabela("SELECT concat( primeiro_nome, ' ', sobrenome ) AS 'nome',id_locacao, data_locacao, data_devolucao, status, valor_total FROM locacao JOIN cliente USING ( id_cliente ) WHERE data_devolucao = curdate( ) and status like '%em aberto%'");        
        
    }

    
    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String [] {"ID","Cliente","Locação", "Devolução","Status", "Total"};
        conexao.conexao();
            conexao.executaSql(Sql);
            try{
               conexao.rs.first();
               do{
                   dados.add(new Object[]{conexao.rs.getString("id_locacao"), conexao.rs.getString("nome"), conexao.rs.getString("data_locacao"), conexao.rs.getDate("data_devolucao"), conexao.rs.getString("status"), conexao.rs.getString("valor_total")});
                   
               }while(conexao.rs.next());
            }catch (SQLException ex){
                JOptionPane.showMessageDialog(rootPane,"Não há devoluções para a data de hoje!");
            }
            ModelBeans.BeansTabela modelo = new ModelBeans.BeansTabela(dados, colunas);
            jTableDevolucoes.setModel(modelo);
            //IDLOCACAO 
            jTableDevolucoes.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTableDevolucoes.getColumnModel().getColumn(0).setResizable(false);
            //CLIENTE 
            jTableDevolucoes.getColumnModel().getColumn(1).setPreferredWidth(220);
            jTableDevolucoes.getColumnModel().getColumn(1).setResizable(false);
            //DATA LOCACAO
            jTableDevolucoes.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableDevolucoes.getColumnModel().getColumn(2).setResizable(false);
            //DATA DEVOLUCAO
            jTableDevolucoes.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableDevolucoes.getColumnModel().getColumn(3).setResizable(false);
            //STATUS
            jTableDevolucoes.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTableDevolucoes.getColumnModel().getColumn(4).setResizable(false);
            //TOTAL
            jTableDevolucoes.getColumnModel().getColumn(5).setPreferredWidth(63);
            jTableDevolucoes.getColumnModel().getColumn(5).setResizable(false);
            //NAO PODE REORDENAR O CABEÇALHO DA TABELA
            jTableDevolucoes.getTableHeader().setReorderingAllowed(false);
            //NAO PODE SER REDIMENCIONADA 
            jTableDevolucoes.setAutoResizeMode(jTableDevolucoes.AUTO_RESIZE_OFF);
            //SO PODERA SELECIONAR UM DADO NA TABELA DE CADA VEZ 
            jTableDevolucoes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexao.desconecta();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonVoltar = new javax.swing.JButton();
        jButtonReceberFilme = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDevolucoes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setLayout(null);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/voltar.png"))); // NOI18N
        jButtonVoltar.setText(" Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVoltar);
        jButtonVoltar.setBounds(20, 330, 130, 50);

        jButtonReceberFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receber 20.png"))); // NOI18N
        jButtonReceberFilme.setText("Receber Filme");
        jButtonReceberFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceberFilmeActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonReceberFilme);
        jButtonReceberFilme.setBounds(210, 280, 210, 40);

        jTableDevolucoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableDevolucoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDevolucoesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDevolucoes);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(22, 40, 600, 230);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 128, 76));
        jLabel1.setText("Devoluções Para o dia de hoje");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(180, 10, 270, 21);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fundo 2.jpg"))); // NOI18N
        jPanel2.add(Fundo);
        Fundo.setBounds(-3, -11, 650, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaPrincipal t = new TelaPrincipal();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonReceberFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceberFilmeActionPerformed
        BeansDevolucao dev = new BeansDevolucao();
       
        String idlocacao =""+jTableDevolucoes.getValueAt(jTableDevolucoes.getSelectedRow(),0);
        //JOptionPane.showMessageDialog(rootPane, idlocacao);
        conexao.conexao();
            conexao.executaSql("SELECT * from locacao join cliente using (id_cliente) where id_locacao = "+idlocacao+"");
        try {
            if(conexao.rs.first()){
                dev.setIdCliente(conexao.rs.getInt("id_cliente"));
                dev.setIdLocacao(conexao.rs.getInt("id_locacao"));
                dev.setDataDevolucao(conexao.rs.getDate("data_devolucao"));
                dev.setDataLocacao(conexao.rs.getDate("data_locacao"));
                dev.setStatus(conexao.rs.getString("status"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar locacao "+ex);
            ex.printStackTrace();
        }    
        
        dao.devolver(dev);
        
        conexao.desconecta();
        
        preencherTabela("SELECT concat( primeiro_nome, ' ', sobrenome ) AS 'nome',id_locacao, data_locacao, data_devolucao, status, valor_total FROM locacao JOIN cliente USING ( id_cliente ) WHERE data_devolucao = curdate( ) and status like '%em aberto%'");
    }//GEN-LAST:event_jButtonReceberFilmeActionPerformed

    private void jTableDevolucoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDevolucoesMouseClicked
        
    }//GEN-LAST:event_jTableDevolucoesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDevolucao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton jButtonReceberFilme;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDevolucoes;
    // End of variables declaration//GEN-END:variables
}
