/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Exceptions.ModelException;
import ModelConection.ConexaoBD;
import ModelDao.DaoCadCliente;
import ModelBeans.BeansCadCliente;
import ModelBeans.BeansCidade;
import ModelBeans.BeansEstado;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author peterson
 */
public class TelaCadCliente extends javax.swing.JFrame {

    ModelBeans.BeansCadCliente mod = new BeansCadCliente();
    ModelConection.ConexaoBD conexao = new ConexaoBD();
    ModelDao.DaoCadCliente cliente = new DaoCadCliente();
    
    public static final int SALVAR = 0;
    public static final int EDITAR = 1;
    int flag = SALVAR;
    
    
    public TelaCadCliente() {
        initComponents();
        preencherTabela("select * from cliente join cidade using (id_cidade) join estado using (id_estado) order by primeiro_nome");
        preencherEstados();
        preencherCidades();
        
        
        jComboBoxEstado.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
            //To change body of generated methods, choose Tools | Templates.
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadCliente = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jLabelRG = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jFormattedTextFieldNomeCliente = new javax.swing.JFormattedTextField();
        jFormattedTextFieldSobrenomeCliente = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCPFCliente = new javax.swing.JFormattedTextField();
        jFormattedTextFieldRGCliente = new javax.swing.JFormattedTextField();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jComboBoxCidade = new javax.swing.JComboBox<>();
        jFormattedTextFieldEnderecoCliente = new javax.swing.JFormattedTextField();
        jTextFieldBairroCliente = new javax.swing.JTextField();
        jTextFieldNumeroCliente = new javax.swing.JTextField();
        jTextFieldCEPCliente = new javax.swing.JTextField();
        jTextFieldReferenciaCliente = new javax.swing.JTextField();
        jFormattedTextFieldTelefoneCliente = new javax.swing.JFormattedTextField();
        jButtonSalvarCliente = new javax.swing.JButton();
        jLabelSobrenome = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonEditaCliente = new javax.swing.JButton();
        jButtonNovoCliente = new javax.swing.JButton();
        jButtonExcluirCliente = new javax.swing.JButton();
        jButtonPesquisaCliente = new javax.swing.JButton();
        jTextFieldBuscaCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        FundoCadCliente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanelCadCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelCadCliente.setLayout(null);

        jLabelNome.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 128, 0));
        jLabelNome.setText("Nome");
        jPanelCadCliente.add(jLabelNome);
        jLabelNome.setBounds(70, 380, 41, 30);

        jLabelEndereco.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelEndereco.setForeground(new java.awt.Color(255, 128, 0));
        jLabelEndereco.setText("Endereço");
        jPanelCadCliente.add(jLabelEndereco);
        jLabelEndereco.setBounds(550, 330, 68, 40);

        jLabelCidade.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelCidade.setForeground(new java.awt.Color(255, 128, 0));
        jLabelCidade.setText("Cidade");
        jPanelCadCliente.add(jLabelCidade);
        jLabelCidade.setBounds(300, 540, 49, 30);

        jLabelEstado.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelEstado.setForeground(new java.awt.Color(255, 128, 0));
        jLabelEstado.setText("Estado");
        jPanelCadCliente.add(jLabelEstado);
        jLabelEstado.setBounds(60, 540, 49, 30);

        jLabelCPF.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelCPF.setForeground(new java.awt.Color(255, 128, 0));
        jLabelCPF.setText("CPF");
        jPanelCadCliente.add(jLabelCPF);
        jLabelCPF.setBounds(80, 460, 29, 18);

        jLabelRG.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelRG.setForeground(new java.awt.Color(255, 128, 0));
        jLabelRG.setText("RG");
        jPanelCadCliente.add(jLabelRG);
        jLabelRG.setBounds(90, 500, 21, 18);

        jLabelTelefone.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelTelefone.setForeground(new java.awt.Color(255, 128, 0));
        jLabelTelefone.setText("Telefone");
        jPanelCadCliente.add(jLabelTelefone);
        jLabelTelefone.setBounds(560, 500, 63, 30);

        jFormattedTextFieldNomeCliente.setBorder(null);
        jFormattedTextFieldNomeCliente.setEnabled(false);
        jFormattedTextFieldNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldNomeClienteActionPerformed(evt);
            }
        });
        jPanelCadCliente.add(jFormattedTextFieldNomeCliente);
        jFormattedTextFieldNomeCliente.setBounds(120, 380, 410, 30);

        jFormattedTextFieldSobrenomeCliente.setEnabled(false);
        jFormattedTextFieldSobrenomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldSobrenomeClienteActionPerformed(evt);
            }
        });
        jPanelCadCliente.add(jFormattedTextFieldSobrenomeCliente);
        jFormattedTextFieldSobrenomeCliente.setBounds(120, 420, 410, 27);

        jFormattedTextFieldCPFCliente.setEnabled(false);
        jPanelCadCliente.add(jFormattedTextFieldCPFCliente);
        jFormattedTextFieldCPFCliente.setBounds(120, 460, 410, 27);

        jFormattedTextFieldRGCliente.setEnabled(false);
        jPanelCadCliente.add(jFormattedTextFieldRGCliente);
        jFormattedTextFieldRGCliente.setBounds(120, 500, 410, 27);

        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione estado..", "Paraná", "Santa Catarina", "São Paulo", "Minas Gerais" }));
        jComboBoxEstado.setEnabled(false);
        jComboBoxEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEstadoItemStateChanged(evt);
            }
        });
        jComboBoxEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxEstadoMouseClicked(evt);
            }
        });
        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });
        jPanelCadCliente.add(jComboBoxEstado);
        jComboBoxEstado.setBounds(120, 540, 170, 27);

        jComboBoxCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione cidade..", "Guarapuava", "Joinvile", "São Paulo Capital", "Turvo", "Pitanga", "Jaciaba" }));
        jComboBoxCidade.setEnabled(false);
        jComboBoxCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCidadeActionPerformed(evt);
            }
        });
        jPanelCadCliente.add(jComboBoxCidade);
        jComboBoxCidade.setBounds(360, 540, 170, 27);

        jFormattedTextFieldEnderecoCliente.setEnabled(false);
        jPanelCadCliente.add(jFormattedTextFieldEnderecoCliente);
        jFormattedTextFieldEnderecoCliente.setBounds(630, 340, 410, 27);

        jTextFieldBairroCliente.setEnabled(false);
        jTextFieldBairroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroClienteActionPerformed(evt);
            }
        });
        jPanelCadCliente.add(jTextFieldBairroCliente);
        jTextFieldBairroCliente.setBounds(630, 380, 220, 27);

        jTextFieldNumeroCliente.setEnabled(false);
        jPanelCadCliente.add(jTextFieldNumeroCliente);
        jTextFieldNumeroCliente.setBounds(930, 380, 110, 27);

        jTextFieldCEPCliente.setEnabled(false);
        jTextFieldCEPCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCEPClienteActionPerformed(evt);
            }
        });
        jPanelCadCliente.add(jTextFieldCEPCliente);
        jTextFieldCEPCliente.setBounds(630, 420, 410, 27);

        jTextFieldReferenciaCliente.setEnabled(false);
        jPanelCadCliente.add(jTextFieldReferenciaCliente);
        jTextFieldReferenciaCliente.setBounds(630, 460, 410, 27);

        jFormattedTextFieldTelefoneCliente.setEnabled(false);
        jPanelCadCliente.add(jFormattedTextFieldTelefoneCliente);
        jFormattedTextFieldTelefoneCliente.setBounds(630, 500, 410, 27);

        jButtonSalvarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salvar.png"))); // NOI18N
        jButtonSalvarCliente.setText(" Salvar dados do cliente");
        jButtonSalvarCliente.setEnabled(false);
        jButtonSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarClienteActionPerformed(evt);
            }
        });
        jPanelCadCliente.add(jButtonSalvarCliente);
        jButtonSalvarCliente.setBounds(710, 540, 240, 50);

        jLabelSobrenome.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelSobrenome.setForeground(new java.awt.Color(255, 128, 0));
        jLabelSobrenome.setText("Sobrenome");
        jPanelCadCliente.add(jLabelSobrenome);
        jLabelSobrenome.setBounds(30, 410, 81, 40);

        jButtonVoltar.setText("Sair");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanelCadCliente.add(jButtonVoltar);
        jButtonVoltar.setBounds(70, 280, 140, 40);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 128, 0));
        jLabel3.setText("Bairro");
        jPanelCadCliente.add(jLabel3);
        jLabel3.setBounds(580, 380, 50, 30);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 128, 0));
        jLabel4.setText("Número");
        jPanelCadCliente.add(jLabel4);
        jLabel4.setBounds(860, 380, 56, 30);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 128, 0));
        jLabel5.setText("CEP");
        jPanelCadCliente.add(jLabel5);
        jLabel5.setBounds(590, 420, 29, 30);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 128, 0));
        jLabel6.setText("Referência");
        jPanelCadCliente.add(jLabel6);
        jLabel6.setBounds(540, 460, 90, 30);

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableClientes);

        jPanelCadCliente.add(jScrollPane2);
        jScrollPane2.setBounds(250, 50, 790, 270);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adicionar.png"))); // NOI18N
        jPanelCadCliente.add(jLabel2);
        jLabel2.setBounds(20, 20, 40, 40);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/configurações.png"))); // NOI18N
        jPanelCadCliente.add(jLabel7);
        jLabel7.setBounds(20, 90, 40, 40);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lixeira.png"))); // NOI18N
        jPanelCadCliente.add(jLabel8);
        jLabel8.setBounds(20, 160, 40, 40);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/voltar.png"))); // NOI18N
        jPanelCadCliente.add(jLabel9);
        jLabel9.setBounds(20, 280, 40, 40);

        jButtonEditaCliente.setText("Editar Cliente");
        jButtonEditaCliente.setEnabled(false);
        jButtonEditaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditaClienteActionPerformed(evt);
            }
        });
        jPanelCadCliente.add(jButtonEditaCliente);
        jButtonEditaCliente.setBounds(70, 90, 140, 40);

        jButtonNovoCliente.setText("Novo Cliente");
        jButtonNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoClienteActionPerformed(evt);
            }
        });
        jPanelCadCliente.add(jButtonNovoCliente);
        jButtonNovoCliente.setBounds(70, 20, 140, 40);

        jButtonExcluirCliente.setText("Excluir Cliente");
        jButtonExcluirCliente.setEnabled(false);
        jButtonExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirClienteActionPerformed(evt);
            }
        });
        jPanelCadCliente.add(jButtonExcluirCliente);
        jButtonExcluirCliente.setBounds(70, 160, 140, 40);

        jButtonPesquisaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buscar20.png"))); // NOI18N
        jButtonPesquisaCliente.setText("Buscar Cliente");
        jButtonPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaClienteActionPerformed(evt);
            }
        });
        jPanelCadCliente.add(jButtonPesquisaCliente);
        jButtonPesquisaCliente.setBounds(550, 10, 180, 29);
        jPanelCadCliente.add(jTextFieldBuscaCliente);
        jTextFieldBuscaCliente.setBounds(250, 10, 290, 27);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/limpar40.png"))); // NOI18N
        jPanelCadCliente.add(jLabel10);
        jLabel10.setBounds(20, 220, 40, 40);

        jButtonLimpar.setText("Limpar Campos");
        jButtonLimpar.setEnabled(false);
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        jPanelCadCliente.add(jButtonLimpar);
        jButtonLimpar.setBounds(70, 220, 140, 40);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 128, 0));
        jLabel11.setText("ID");
        jPanelCadCliente.add(jLabel11);
        jLabel11.setBounds(100, 350, 30, 18);

        jTextFieldID.setEnabled(false);
        jPanelCadCliente.add(jTextFieldID);
        jTextFieldID.setBounds(120, 340, 70, 27);

        FundoCadCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FundoCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fundo 2.jpg"))); // NOI18N
        jPanelCadCliente.add(FundoCadCliente);
        FundoCadCliente.setBounds(0, -30, 1080, 680);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adicionar 25.png"))); // NOI18N
        jLabel1.setText("Cadastro de Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        setSize(new java.awt.Dimension(1071, 671));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    public void preencherEstados(){    
        jComboBoxEstado.removeAllItems();
                
        for(BeansEstado be : BeansEstado.buscarTodos()){
            jComboBoxEstado.addItem(be.getNome());
        }
        
        jComboBoxEstado.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                preencherCidades();
            }
        });
        
    }
 
    public void preencherCidades(){
    
        jComboBoxCidade.removeAllItems();
        
        for(BeansCidade bc : BeansCidade.buscarTodos(jComboBoxEstado.getSelectedItem().toString())){
            
            jComboBoxCidade.addItem(bc.getNome());
        }
    }
    
    private void jFormattedTextFieldNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldNomeClienteActionPerformed

    private void jFormattedTextFieldSobrenomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldSobrenomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldSobrenomeClienteActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaPrincipal t = new TelaPrincipal();
        t.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jTextFieldBairroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroClienteActionPerformed

    private void jTextFieldCEPClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCEPClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCEPClienteActionPerformed

    private void jButtonSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarClienteActionPerformed
        
        BeansCadCliente clienteAtual = new BeansCadCliente();
        
        try{
            clienteAtual.setNome(jFormattedTextFieldNomeCliente.getText());
            clienteAtual.setSobrenome(jFormattedTextFieldSobrenomeCliente.getText());
            clienteAtual.setCpf(jFormattedTextFieldCPFCliente.getText());
            clienteAtual.setRg(jFormattedTextFieldRGCliente.getText());
            clienteAtual.setEstado((String) jComboBoxEstado.getSelectedItem().toString());
            clienteAtual.setCidade((String) jComboBoxCidade.getSelectedItem().toString());
            clienteAtual.setEndereco(jFormattedTextFieldEnderecoCliente.getText());
            clienteAtual.setBairro(jTextFieldBairroCliente.getText());
            
            
            clienteAtual.setNumero(Integer.parseInt(jTextFieldNumeroCliente.getText()));
            
            clienteAtual.setCep(jTextFieldCEPCliente.getText());
            clienteAtual.setReferencia(jTextFieldReferenciaCliente.getText());
            clienteAtual.setTelefone(jFormattedTextFieldTelefoneCliente.getText());
            
            clienteAtual.setId_cidade(BeansCidade.buscarPorNome(jComboBoxCidade.getSelectedItem().toString(), jComboBoxEstado.getSelectedItem().toString()).getId());
            
            if(flag == EDITAR){
               
                clienteAtual.setId((Integer.parseInt(jTextFieldID.getText())));
                
            }
            clienteAtual.salvar();
            
            jTextFieldBairroCliente.setEnabled(false);
            jTextFieldBuscaCliente.setEnabled(false);
            jTextFieldCEPCliente.setEnabled(false);
            jTextFieldNumeroCliente.setEnabled(false);
            jTextFieldReferenciaCliente.setEnabled(false);
            jFormattedTextFieldCPFCliente.setEnabled(false);
            jFormattedTextFieldEnderecoCliente.setEnabled(false);
            jFormattedTextFieldNomeCliente.setEnabled(false);
            jFormattedTextFieldRGCliente.setEnabled(false);
            jFormattedTextFieldSobrenomeCliente.setEnabled(false);
            jFormattedTextFieldTelefoneCliente.setEnabled(false);
            jComboBoxEstado.setEnabled(false);
            jComboBoxCidade.setEnabled(false);
            jButtonSalvarCliente.setEnabled(false);
            jButtonNovoCliente.setEnabled(true);
            jButtonEditaCliente.setEnabled(false);
            jTextFieldBuscaCliente.setEnabled(true);
            
            
            //JOptionPane.showMessageDialog(null, "Dados salvos!");
            jButtonLimparActionPerformed(evt);
            
            preencherTabela("select * from cliente join cidade using (id_cidade) join estado using (id_estado) order by primeiro_nome;");
        
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Verifique os campos numéricos!");
        }catch(ModelException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSalvarClienteActionPerformed

    public void preencherTabela(String Sql){
        ArrayList dados = new ArrayList();
        String [] colunas = new String [] {"Nome","Sobrenome", "RG", "CPF", "Cidade", "UF", "Telefone"};
        conexao.conexao();
            conexao.executaSql(Sql);
            try{
               conexao.rs.first();
               do{
                   dados.add(new Object[]{conexao.rs.getString("primeiro_nome"), conexao.rs.getString("sobrenome"), conexao.rs.getString("rg"), conexao.rs.getString("cpf"), conexao.rs.getString("cidade.nome"), conexao.rs.getString("estado.uf"), conexao.rs.getString("telefone")});
                   
               }while(conexao.rs.next());
            }catch (SQLException ex){
                JOptionPane.showMessageDialog(rootPane,"Erro ao preencher tabela");
            }
            ModelBeans.BeansTabela modelo = new ModelBeans.BeansTabela(dados, colunas);
            jTableClientes.setModel(modelo);
            //PRIMEIRO NOME 
            jTableClientes.getColumnModel().getColumn(0).setPreferredWidth(135);
            jTableClientes.getColumnModel().getColumn(0).setResizable(false);
            //SOBRENOME
            jTableClientes.getColumnModel().getColumn(1).setPreferredWidth(105);
            jTableClientes.getColumnModel().getColumn(1).setResizable(false);
            //RG
            jTableClientes.getColumnModel().getColumn(2).setPreferredWidth(115);
            jTableClientes.getColumnModel().getColumn(2).setResizable(false);
            //CPF
            jTableClientes.getColumnModel().getColumn(3).setPreferredWidth(115);
            jTableClientes.getColumnModel().getColumn(3).setResizable(false);
            //NOME DA CIDADE
            jTableClientes.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTableClientes.getColumnModel().getColumn(4).setResizable(false);
            //NOME DO ESTADO
            jTableClientes.getColumnModel().getColumn(5).setPreferredWidth(50);
            jTableClientes.getColumnModel().getColumn(5).setResizable(false);
            //TELEFONE
            jTableClientes.getColumnModel().getColumn(6).setPreferredWidth(114);
            jTableClientes.getColumnModel().getColumn(6).setResizable(false);
            //NAO PODE REORDENAR O CABEÇALHO DA TABELA
            jTableClientes.getTableHeader().setReorderingAllowed(false);
            //NAO PODE SER REDIMENCIONADA 
            jTableClientes.setAutoResizeMode(jTableClientes.AUTO_RESIZE_OFF);
            //SO PODERA SELECIONAR UM DADO NA TABELA DE CADA VEZ 
            jTableClientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conexao.desconecta();
    }
    
    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
        
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

    private void jComboBoxEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxEstadoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBoxEstadoMouseClicked

    private void jComboBoxCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCidadeActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCidadeActionPerformed

    private void jButtonNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoClienteActionPerformed
    
    flag = SALVAR;
        //APAGANDO TUDO O QUE TEM NOS CAMPOS DE TEXTO
        jTextFieldID.setText("");
        jTextFieldBairroCliente.setText("");
        jTextFieldBuscaCliente.setText("");
        jTextFieldCEPCliente.setText("");
        jTextFieldNumeroCliente.setText("");
        jTextFieldReferenciaCliente.setText("");
        jFormattedTextFieldCPFCliente.setText("");
        jFormattedTextFieldEnderecoCliente.setText("");
        jFormattedTextFieldNomeCliente.setText("");
        jFormattedTextFieldRGCliente.setText("");
        jFormattedTextFieldSobrenomeCliente.setText("");
        jFormattedTextFieldTelefoneCliente.setText("");
        
        //LIBERANDO OS CAMPOS DE TEXTOS 
        jTextFieldBairroCliente.setEnabled(true);
        jTextFieldBuscaCliente.setEnabled(true);
        jTextFieldCEPCliente.setEnabled(true);
        jTextFieldNumeroCliente.setEnabled(true);
        jTextFieldReferenciaCliente.setEnabled(true);
        jFormattedTextFieldCPFCliente.setEnabled(true);
        jFormattedTextFieldEnderecoCliente.setEnabled(true);
        jFormattedTextFieldNomeCliente.setEnabled(true);
        jFormattedTextFieldRGCliente.setEnabled(true);
        jFormattedTextFieldSobrenomeCliente.setEnabled(true);
        jFormattedTextFieldTelefoneCliente.setEnabled(true);
        jComboBoxEstado.setEnabled(true);
        jComboBoxCidade.setEnabled(true);
        jButtonSalvarCliente.setEnabled(true);
        jButtonLimpar.setEnabled(true);
        jButtonEditaCliente.setEnabled(false);
        
    }//GEN-LAST:event_jButtonNovoClienteActionPerformed

    private void jButtonPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaClienteActionPerformed
        mod.setPesquisa(jTextFieldBuscaCliente.getText());
        
        BeansCadCliente model = cliente.buscaCliente(jTextFieldBuscaCliente.getText());
        
        //BeansCadCliente model = cliente.buscaCliente(mod);
        jTextFieldID.setText(String.valueOf(model.getId()));
        jTextFieldBairroCliente.setText(model.getBairro());
        jTextFieldCEPCliente.setText(model.getCep());
        jTextFieldNumeroCliente.setText(String.valueOf(model.getNumero()));
        jTextFieldReferenciaCliente.setText(model.getReferencia());
        jFormattedTextFieldCPFCliente.setText(model.getCpf());
        jFormattedTextFieldEnderecoCliente.setText(model.getEndereco());
        jFormattedTextFieldNomeCliente.setText(model.getNome());
        jFormattedTextFieldRGCliente.setText(model.getRg());
        jFormattedTextFieldSobrenomeCliente.setText(model.getSobrenome());
        jFormattedTextFieldTelefoneCliente.setText(model.getTelefone());
        jComboBoxEstado.setSelectedItem(model.getEstado());
        jComboBoxCidade.setSelectedItem(model.getCidade());
        
        //SABER O QUE O MODEL E A CIDADE RETORNAM
        //JOptionPane.showMessageDialog(rootPane, "estado "+model.getEstado()+ " cidade "+model.getCidade());
        
        //LIBERANDO BOTAO EDITAR
        jButtonEditaCliente.setEnabled(true);
        //LIBERANDO BOTAO EXCLUIR
        jButtonExcluirCliente.setEnabled(true);
        //LIBERANDO BOTAO LIMPAR DADOS
        jButtonLimpar.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisaClienteActionPerformed

    private void jButtonEditaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditaClienteActionPerformed
    flag = EDITAR;
        jTextFieldBairroCliente.setEnabled(true);
        jTextFieldBuscaCliente.setEnabled(true);
        jTextFieldCEPCliente.setEnabled(true);
        jTextFieldNumeroCliente.setEnabled(true);
        jTextFieldReferenciaCliente.setEnabled(true);
        jFormattedTextFieldCPFCliente.setEnabled(true);
        jFormattedTextFieldEnderecoCliente.setEnabled(true);
        jFormattedTextFieldNomeCliente.setEnabled(true);
        jFormattedTextFieldRGCliente.setEnabled(true);
        jFormattedTextFieldSobrenomeCliente.setEnabled(true);
        jFormattedTextFieldTelefoneCliente.setEnabled(true);
        jComboBoxEstado.setEnabled(true);
        jComboBoxCidade.setEnabled(true);
        jButtonSalvarCliente.setEnabled(true);
        jButtonLimpar.setEnabled(true);
        
        jButtonExcluirCliente.setEnabled(false);
        jButtonNovoCliente.setEnabled(true);
        jButtonLimpar.setEnabled(false);
    }//GEN-LAST:event_jButtonEditaClienteActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldID.setText("");
        jTextFieldBairroCliente.setText("");
        jTextFieldBuscaCliente.setText("");
        jTextFieldCEPCliente.setText("");
        jTextFieldNumeroCliente.setText("");
        jTextFieldReferenciaCliente.setText("");
        jFormattedTextFieldCPFCliente.setText("");
        jFormattedTextFieldEnderecoCliente.setText("");
        jFormattedTextFieldNomeCliente.setText("");
        jFormattedTextFieldRGCliente.setText("");
        jFormattedTextFieldSobrenomeCliente.setText("");
        jFormattedTextFieldTelefoneCliente.setText("");
        jComboBoxEstado.setEnabled(false);
        jComboBoxCidade.setEnabled(false);
        jButtonSalvarCliente.setEnabled(false);
        jButtonNovoCliente.setEnabled(true);
        jButtonEditaCliente.setEnabled(false);
        jButtonExcluirCliente.setEnabled(false);
        jButtonLimpar.setEnabled(false);
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirClienteActionPerformed
        int resposta = 0;
      
        
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir o cliente "+jFormattedTextFieldNomeCliente.getText() +"?");
        if (resposta == JOptionPane.YES_OPTION){
            mod.setId(Integer.parseInt(jTextFieldID.getText()));
          
            try{
                cliente.excluir(mod);
            }catch(RuntimeException ex){
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
                
            jButtonSalvarCliente.setEnabled(false);
            jButtonLimpar.setEnabled(false);       
            jButtonExcluirCliente.setEnabled(false);
            jButtonEditaCliente.setEnabled(false);
            
        }
        //preencherTabela("select * from cliente join cidade using (id_cidade) join estado using (id_estado) order by primeiro_nome;");
        jButtonLimparActionPerformed(evt);
    }//GEN-LAST:event_jButtonExcluirClienteActionPerformed

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        String nome =""+jTableClientes.getValueAt(jTableClientes.getSelectedRow(),0);
        //JOptionPane.showMessageDialog(rootPane, nome);
        conexao.conexao();
        conexao.executaSql("SELECT *, cidade.nome, estado.nome FROM cliente JOIN cidade USING ( id_cidade ) JOIN estado USING ( id_estado ) WHERE cliente.primeiro_nome LIKE '%"+nome+"%' order by primeiro_nome");
        
        try {
            if(conexao.rs.first()){
                jTextFieldID.setText(String.valueOf(conexao.rs.getInt("id_cliente")));
                jTextFieldBairroCliente.setText(conexao.rs.getString("bairro"));
                jTextFieldCEPCliente.setText(conexao.rs.getString("cep"));
                jTextFieldNumeroCliente.setText(String.valueOf(conexao.rs.getInt("numero")));
                jTextFieldReferenciaCliente.setText(conexao.rs.getString("referencia"));
                jFormattedTextFieldCPFCliente.setText(conexao.rs.getString("cpf"));
                jFormattedTextFieldEnderecoCliente.setText(conexao.rs.getString("rua"));
                jFormattedTextFieldNomeCliente.setText(conexao.rs.getString("primeiro_nome"));
                jFormattedTextFieldRGCliente.setText(conexao.rs.getString("rg"));
                jFormattedTextFieldSobrenomeCliente.setText(conexao.rs.getString("sobrenome"));
                jFormattedTextFieldTelefoneCliente.setText(conexao.rs.getString("telefone"));
                jComboBoxEstado.setSelectedItem(conexao.rs.getString("estado.nome"));
                jComboBoxCidade.setSelectedItem(conexao.rs.getString("cidade.nome"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar cliente "+ex);
            ex.printStackTrace();
        }    
        conexao.desconecta();
        jButtonEditaCliente.setEnabled(true);
        jButtonExcluirCliente.setEnabled(true);
        
    }//GEN-LAST:event_jTableClientesMouseClicked

    private void jComboBoxEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEstadoItemStateChanged
        //preencherCidades();
    }//GEN-LAST:event_jComboBoxEstadoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FundoCadCliente;
    private javax.swing.JButton jButtonEditaCliente;
    private javax.swing.JButton jButtonExcluirCliente;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonNovoCliente;
    private javax.swing.JButton jButtonPesquisaCliente;
    private javax.swing.JButton jButtonSalvarCliente;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox<String> jComboBoxCidade;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPFCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldEnderecoCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldNomeCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldRGCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldSobrenomeCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefoneCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelRG;
    private javax.swing.JLabel jLabelSobrenome;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JPanel jPanelCadCliente;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTextFieldBairroCliente;
    private javax.swing.JTextField jTextFieldBuscaCliente;
    private javax.swing.JTextField jTextFieldCEPCliente;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldNumeroCliente;
    private javax.swing.JTextField jTextFieldReferenciaCliente;
    // End of variables declaration//GEN-END:variables
}
